name: Generate Snake

on:
  schedule:
    - cron: "*/15 * * * *"  # every 15 minutes (GitHub's fastest allowed interval)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: BowerH
          outputs: |
            dist/github-contribution-grid-snake.svg
          # 🌈 Rainbow snake colors
          color_snake: rainbow
          color_dots: "#ebedf0,#c6e48b,#7bc96f,#239a3b,#196127"

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
