name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # once a day
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation (dark mode)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: BowerH
          outputs: |
            dist/github-contribution-grid-snake.svg
          color_snake: rainbow
          color_dots: "#161B22,#0D1117,#30363D,#3FB950,#26A641"

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
